services:
  portfolio:
    build: .
    container_name: portfolio
    restart: unless-stopped
    networks:
      - shared-nginx
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

networks:
  shared-nginx:
    external: true
